[package]
name = "dungeon"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
rand = "0.3.0"

[lib]
name = "dungeon"
path = "src/lib.rs"

[dev-dependencies]
allegro = "0.0.22"
allegro-sys = "0.0.22"
allegro_primitives = "0.0.22"
allegro_font = "0.0.22"

